### ISSUE TITLE
Fulcio unable to verify/retrieve Google Certificate Authority url path

### ISSUE THREAD

**Issue by acald-creator** [stacklok/sigstore-the-hard-way#13]
First off, I want to say, I am a newcomer on Sigstore projects, but so far, I am loving the projects and I want to become involved in the process as well, so I'm making my way through each of the repositories and see what I can do. While I was doing that, I came across this tutorial so I can set it up myself within GCP and any other cloud platforms.

The one issue I came across is setting up Fulcio with Google Certificate Authority. Instead of installing SoftHSM on the server, I wanted to utilize Google Certificate Authority. Here are the steps I've done once I completed the tutorial.

I run `fulcio` with the latest version.

`/usr/local/bin/fulcio serve --config-path=/etc/fulcio-config/config.json --ca googleca --gcp_private_ca_parent=projects/<PROJECT_NAME>/locations/us-central1/caPools/<CA_POOL>/certificateAuthorities/20220602-xxx-xxx --ct-log-url http://sigstore-ctl:6105/sigstore --host=0.0.0.0 --port=5000 --log_type prod`

In another terminal, I run `cosign` and this is the latest version of `cosign`.

`COSIGN_EXPERIMENTAL=1 cosign sign --oidc-issuer "https://oauth2.phxvlabs.dev/auth" --fulcio-url "https://fulcio.phxvlabs.dev" --rekor-url "https://rekor.phxvlabs.dev" ghcr.io/acald-creator/sigstore-thw:latest --verbose`

Error message:

`main.go:52: error during command execution: signing [ghcr.io/acald-creator/sigstore-thw:latest]: getting signer: getting key from Fulcio: retrieving cert: {"code":3, "message":"rpc error: code = InvalidArgument desc = Malformed collection name: 'caPools/certificateAuthorities/certificates'", "details":[]}`

I found this configuration information from `fulcio` repository that `fulcio` may be looking for at this pattern `--gcp_private_ca_parent=projects/project-rekor/locations/us-central1/certificateAuthorities/sigstore`  but it didn't work for me because I then get an error

`{"severity":"error","ts":1654272470.232576,"caller":"api/error.go:40","message":"returning with error","requestID":"phwqjTu5","code":"InvalidArgument","clientMessage":"rpc error: code = InvalidArgument desc = The CreateCertificateRequest proto is invalid:\\n  * parent: The parent field does not match the expected pattern."`

Please note that I have tore down Fulcio server and rebuilt it a few times to see if the error came up, and so far it has. Any suggestions?

**Comment by lukehinds** [comment]
I can't say I have seen this before @acald-creator , are you sure the parent name was correct?

**Comment by acald-creator** [comment]
@lukehinds Thanks for reaching out. This was resolved on when I opened a separate issue on sigstore. I forgot to mention it here, but I cannot find the existing issue I had regarding this.

**Comment by lukehinds** [comment]
thanks @acald-creator , pleased its resolved. I will close this for now.
