### ISSUE TITLE
haproxy configuration is incomplete

### ISSUE THREAD

**Issue by avoidik** [stacklok/sigstore-the-hard-way#5]
hello,

while following the chapters I noticed that the haproxy configuration in chapters rekor and dex are incomplete, however in the fulcio chapter it looks good, could you please check?

**Comment by lukehinds** [comment]
sure!

**Comment by avoidik** [comment]
I think I understand why haproxy configuration is left like that, there are two approaches to that:
1. bootstrap certificates manually using certbot CLI, and then in haproxy configuration pass acme request through to certbot, this would require changes to letsencrypt configuration file for automatic renewal, also a post hook script to concatenate certificates and reload haproxy service
1. a certbot hooks to stop haproxy before renewal, and run it afterward

**Comment by avoidik** [comment]
the first approach is reflected in https://github.com/lukehinds/sigstore-the-hard-way/pull/6
