### ISSUE TITLE
FulcioCA is now PKCS11CA

### ISSUE THREAD

**Issue by rgerganov** [stacklok/sigstore-the-hard-way#7]
FulcioCA has been renamed to PKCS11CA with this commit: https://github.com/sigstore/fulcio/commit/fd319cf07e368e41e11a79c0c9f29d67e07b8579

The instructions for setting up Fulcio needs to be updated

**Comment by rgerganov** [comment]
Sorry, I just noticed that the guide is using Fulcio v0.1.1 while I am running the current master.

**Comment by lukehinds** [comment]
Hey @rgerganov , I think it makes sense to update once Fulcio is 1.0 (should be shortly).

Thanks and hope this is useful (sigstore the hard way)
